### ISSUE TITLE
Will this work with Ansible-pull?

### ISSUE THREAD

**Issue by MrMMorris** [balanced-ops/citadel-ansible#3]
Thank so much for porting over the beauty that it Citadel to the Ansible world. It was a big thing missing coming from the Chef ecosystem!

**Question:** I use ansible-pull for Continuous Deployment. Can this be used along with that? Just have it in the playbook repo that is pulled to the server? Where would I save the plugin?

Thanks again

**Comment by mahmoudimus** [comment]
@MrMMorris - yes, you may use this with `ansible-pull`. It works great, just keep it in the playbook repo that is pulled from the server.

**Comment by MrMMorris** [comment]
thanks!
