### ISSUE TITLE
Weird error with ansible-pull

### ISSUE THREAD

**Issue by MrMMorris** [balanced-ops/citadel-ansible#6]
Me again :wink: 

This may have nothing to do with the plugin, but I have gotten into the habit of asking anyways instead of banging my head.

I have this role:

```yaml
- debug: var=id_dev
```

and vars/main.yml:

```yaml
id_dev: "{{ lookup('citadel', '/sensitive/id_non_prod').strip() }}"
```

Running from my local works fine. Running the EXACT same task with ansible-pull results in this error:

```
TASK: [tv | include_vars main.yml] ****************************************
fatal: [localhost] => Unexpected error in during lookup: cannot concatenate 'str' and 'NoneType' objects
```

At first I thought it just couldn't find my lookup_plugin directory, but that's not it. 

Any ideas? I will create an issue for ansible-pull if not

**Comment by mjallday** [comment]
I've had this error before and it was related to the specific version of ansible that I had installed at the time. I have no further information right now but wanted to mention that.

**Comment by MrMMorris** [comment]
@mjallday that's a start! I think I am running the latest (1.9). I will double check and if so maybe submit a ticket on the ansible repo

**Comment by mjallday** [comment]
@MrMMorris not sure if you're still having this issue. i also ran into it and used the follow code:

```diff
+        if 'inventory_hostname' in inject and inject['inventory_hostname'] in inject:
+            inject = inject[inject['inventory_hostname']]
+
```
and put it in here https://github.com/balanced-ops/citadel-ansible/blob/master/s3lookup.py#L71
